FROM jgphilpott/flask-pack:base

RUN pip install --upgrade pip

RUN pip install numpy
RUN pip install scipy

RUN pip install Flask-Mail

RUN pip install matplotlib
RUN pip install altair

RUN pip install pandas
RUN pip install scikit-learn

RUN pip install tensorflow
RUN pip install Keras
