FROM python:3.8-alpine

RUN pip install --upgrade pip

RUN pip install Flask
RUN pip install fire

RUN pip install pytest

RUN pip install pymongo

RUN pip install gpiozero

RUN pip install guizero
RUN pip install colorzero
